import type { CategoryId, NodeDefinition } from './types';

export const categories: Array<{ id: CategoryId; name: string; short: string }> = [
  { id: 'entry', name: '流量入口', short: '入口' },
  { id: 'service', name: '应用服务', short: '服务' },
  { id: 'data', name: '数据存储', short: '数据' },
  { id: 'message', name: '消息系统', short: '消息' },
  { id: 'governance', name: '服务治理', short: '治理' },
  { id: 'observability', name: '可观测性', short: '观测' },
];

const commonServiceFields = [
  { key: 'latency', label: '基础延迟', type: 'number' as const, unit: 'ms', min: 0, help: '模拟单次请求的基础处理时间' },
  { key: 'concurrency', label: '最大并发', type: 'number' as const, unit: 'req', min: 1 },
  { key: 'failureRate', label: '失败概率', type: 'number' as const, unit: '%', min: 0, max: 100 },
];

export const nodeCatalog: NodeDefinition[] = [
  {
    type: 'client', name: '客户端', subtitle: 'Client', category: 'entry', icon: '◫', color: '#52b6ff',
    description: '系统请求的起点，可以代表浏览器、移动 App、IoT 设备或外部调用方。',
    usage: ['配置请求方法、路径和请求体', '作为运行场景的入口节点', '观察端到端响应时间'],
    principles: ['客户端通过 HTTP、WebSocket 或 RPC 与服务端通信。', '重试、超时和幂等设计会直接影响后端负载。'],
    pitfalls: ['无限重试可能引发流量放大', '敏感凭证不应明文保存在客户端'],
    tags: ['HTTP', '入口', '请求'], maxInstances: 4,
    configFields: [
      { key: 'method', label: '请求方法', type: 'select', options: ['GET', 'POST', 'PUT', 'DELETE'] },
      { key: 'path', label: '请求路径', type: 'text' },
      { key: 'timeout', label: '超时时间', type: 'number', unit: 'ms', min: 100 },
    ],
    defaults: { method: 'POST', path: '/api/orders', timeout: 3000 },
  },
  {
    type: 'load-balancer', name: '负载均衡器', subtitle: 'Load Balancer', category: 'entry', icon: '⇆', color: '#43d2b5',
    description: '把入口流量分配给多个服务实例，提高吞吐能力与可用性。',
    usage: ['部署在入口与服务集群之间', '选择轮询、最少连接或哈希策略', '配合健康检查摘除异常实例'],
    principles: ['四层负载均衡按连接转发，七层负载均衡可感知 HTTP 内容。', '一致性哈希适用于需要会话亲和或缓存定位的场景。'],
    pitfalls: ['单个负载均衡器仍可能成为单点', '会话粘滞会削弱流量均衡效果'],
    tags: ['L4', 'L7', '流量'], maxInstances: 2,
    configFields: [
      { key: 'strategy', label: '调度策略', type: 'select', options: ['Round Robin', 'Least Connections', 'Consistent Hash'] },
      { key: 'healthCheck', label: '健康检查', type: 'boolean' },
    ],
    defaults: { strategy: 'Round Robin', healthCheck: true },
  },
  {
    type: 'api-gateway', name: 'API 网关', subtitle: 'API Gateway', category: 'entry', icon: '◇', color: '#9d82ff',
    description: '统一承接外部 API 流量，集中处理路由、鉴权、限流和协议转换。',
    usage: ['为后端服务配置统一入口', '按路径或请求头路由', '在服务调用前执行认证和限流'],
    principles: ['网关是跨服务关注点的集中处理层。', '避免把复杂业务逻辑堆积在网关中。'],
    pitfalls: ['错误的限流策略会影响正常用户', '网关故障会扩大为全站故障'],
    tags: ['路由', '鉴权', '限流'], maxInstances: 2,
    configFields: [
      { key: 'rateLimit', label: '限流阈值', type: 'number', unit: 'req/s', min: 1 },
      { key: 'auth', label: '开启鉴权', type: 'boolean' },
      ...commonServiceFields.slice(0, 1),
    ],
    defaults: { rateLimit: 1000, auth: true, latency: 8 },
  },
  {
    type: 'backend-service', name: '后端服务', subtitle: 'Backend Service', category: 'service', icon: '⬡', color: '#ffb45e',
    description: '承载领域业务逻辑的应用服务，是拓扑中最主要的计算节点。',
    usage: ['实现订单、用户、商品等领域能力', '通过 API 接收同步调用', '访问缓存、数据库或发布领域事件'],
    principles: ['服务边界应围绕业务能力划分。', '无状态服务更容易进行水平扩展。'],
    pitfalls: ['过度拆分会增加分布式复杂度', '跨服务长事务难以保证一致性'],
    tags: ['REST', '业务', '微服务'], maxInstances: 12,
    configFields: [
      { key: 'serviceName', label: '服务名称', type: 'text' },
      ...commonServiceFields,
      { key: 'replicas', label: '实例数量', type: 'number', unit: '个', min: 1 },
    ],
    defaults: { serviceName: '订单服务', latency: 35, concurrency: 200, failureRate: 1, replicas: 2 },
  },
  {
    type: 'third-party', name: '第三方 API', subtitle: 'External API', category: 'service', icon: '↗', color: '#ff7d90',
    description: '支付、短信、地图等由外部团队或供应商提供的远程能力。',
    usage: ['模拟外部依赖的延迟和失败', '验证重试、超时、熔断与降级策略'],
    principles: ['外部依赖不可控，调用方必须设置超时和隔离。', '幂等键可以避免重试造成重复扣款等副作用。'],
    pitfalls: ['缺少超时会耗尽工作线程', '对非幂等接口盲目重试很危险'],
    tags: ['支付', '外部依赖', 'HTTP'], maxInstances: 5,
    configFields: [...commonServiceFields, { key: 'timeout', label: '调用超时', type: 'number', unit: 'ms', min: 100 }],
    defaults: { latency: 280, concurrency: 50, failureRate: 3, timeout: 1000 },
  },
  {
    type: 'mysql', name: 'MySQL', subtitle: 'Relational DB', category: 'data', icon: '▱', color: '#4f9cff',
    description: '提供事务、索引和关系模型能力的关系型数据库。',
    usage: ['保存核心业务数据', '利用事务保证局部一致性', '通过索引优化高频查询'],
    principles: ['B+Tree 索引减少磁盘访问。', '事务通过 ACID 属性保证可靠的数据变更。'],
    pitfalls: ['缺失索引会造成全表扫描', '连接池过大会反向压垮数据库'],
    tags: ['SQL', '事务', '持久化'], maxInstances: 4,
    configFields: [
      { key: 'poolSize', label: '连接池大小', type: 'number', unit: '条', min: 1 },
      { key: 'latency', label: '查询延迟', type: 'number', unit: 'ms', min: 0 },
      { key: 'transaction', label: '开启事务', type: 'boolean' },
    ],
    defaults: { poolSize: 30, latency: 42, transaction: true },
  },
  {
    type: 'redis', name: 'Redis', subtitle: 'In-memory Cache', category: 'data', icon: '◆', color: '#ff5e66',
    description: '基于内存的高性能数据结构服务器，常用于缓存、计数和分布式锁。',
    usage: ['在服务与数据库之间缓存热点数据', '设置合理 TTL', '用命中率评估缓存价值'],
    principles: ['内存访问使 Redis 具备极低延迟。', '缓存旁路模式由应用负责读取与回填。'],
    pitfalls: ['需要防范穿透、击穿和雪崩', '缓存与数据库可能短暂不一致'],
    tags: ['缓存', 'Key-Value', '高性能'], maxInstances: 4,
    configFields: [
      { key: 'hitRate', label: '缓存命中率', type: 'number', unit: '%', min: 0, max: 100 },
      { key: 'latency', label: '访问延迟', type: 'number', unit: 'ms', min: 0 },
      { key: 'ttl', label: '默认 TTL', type: 'number', unit: 's', min: 1 },
    ],
    defaults: { hitRate: 82, latency: 3, ttl: 300 },
  },
  {
    type: 'kafka', name: 'Kafka', subtitle: 'Event Streaming', category: 'message', icon: '≋', color: '#d7e0ea',
    description: '高吞吐的分布式事件流平台，用于系统解耦、异步处理和事件留存。',
    usage: ['服务发布领域事件', '按 Topic 组织事件', '使用分区提高并行吞吐'],
    principles: ['追加写日志带来高吞吐。', '消费组内一个分区同时只由一个消费者处理。'],
    pitfalls: ['需要处理至少一次语义带来的重复消费', '分区数量影响扩展上限与顺序性'],
    tags: ['事件', '异步', '消息队列'], maxInstances: 3,
    configFields: [
      { key: 'partitions', label: '分区数量', type: 'number', unit: '个', min: 1 },
      { key: 'throughput', label: '生产速率', type: 'number', unit: 'msg/s', min: 1 },
      { key: 'acks', label: '确认级别', type: 'select', options: ['0', '1', 'all'] },
    ],
    defaults: { partitions: 6, throughput: 1000, acks: 'all' },
  },
  {
    type: 'consumer', name: '消息消费者', subtitle: 'Consumer', category: 'message', icon: '⇥', color: '#ebc85f',
    description: '从消息系统拉取事件并执行异步业务逻辑。',
    usage: ['必须先在画布中添加消息队列', '加入消费组实现负载分担', '使用幂等键抵御重复消息'],
    principles: ['消费位点记录处理进度。', '消费速率低于生产速率时会产生消息积压。'],
    pitfalls: ['先提交位点可能造成消息丢失', '处理失败需要重试队列或死信队列'],
    tags: ['消费组', '异步', '事件'], maxInstances: 8,
    requirements: [{ types: ['kafka'], mode: 'any', description: '消息消费者依赖消息系统，请先添加 Kafka。' }],
    configFields: [
      { key: 'groupId', label: '消费组', type: 'text' },
      { key: 'rate', label: '消费速率', type: 'number', unit: 'msg/s', min: 1 },
      { key: 'retry', label: '失败重试', type: 'number', unit: '次', min: 0 },
    ],
    defaults: { groupId: 'order-workers', rate: 300, retry: 3 },
  },
  {
    type: 'envoy', name: 'Envoy', subtitle: 'L7 Proxy', category: 'governance', icon: '◈', color: '#d684ff',
    description: '高性能七层代理，可作为边缘代理或服务 Sidecar，提供路由、重试、熔断和可观测能力。',
    usage: ['先添加 API 网关、负载均衡器或后端服务作为代理目标', '在服务前放置 Envoy', '配置上游集群、超时和重试策略'],
    principles: ['Envoy 通过 Listener、Filter Chain、Cluster 组织流量处理。', 'xDS API 可以动态下发路由与集群配置。'],
    pitfalls: ['重试策略不当可能造成流量放大', 'Sidecar 会增加资源和运维成本'],
    docs: 'https://www.envoyproxy.io/docs',
    tags: ['代理', 'Sidecar', 'xDS', '服务网格'], maxInstances: 8,
    requirements: [{
      types: ['backend-service', 'api-gateway', 'load-balancer'], mode: 'any',
      description: 'Envoy 需要一个可代理的上游目标，请先添加后端服务、API 网关或负载均衡器。',
    }],
    configFields: [
      { key: 'mode', label: '部署模式', type: 'select', options: ['Sidecar', 'Edge Proxy', 'Gateway'] },
      { key: 'timeout', label: '上游超时', type: 'number', unit: 'ms', min: 1 },
      { key: 'retries', label: '重试次数', type: 'number', unit: '次', min: 0, max: 10 },
      { key: 'circuitBreaker', label: '开启熔断', type: 'boolean' },
    ],
    defaults: { mode: 'Sidecar', timeout: 1200, retries: 2, circuitBreaker: true },
  },
  {
    type: 'service-mesh', name: '服务网格控制面', subtitle: 'Service Mesh', category: 'governance', icon: '⌘', color: '#8f7bff',
    description: '集中管理服务间流量策略、安全策略和遥测配置的控制平面。',
    usage: ['先添加 Envoy 和至少两个后端服务', '通过控制面向数据面代理下发策略'],
    principles: ['数据面代理执行流量策略，控制面负责配置分发。', 'mTLS 为服务间通信提供身份和加密。'],
    pitfalls: ['引入网格会提高排障复杂度', '控制面配置错误可能影响大量服务'],
    tags: ['Mesh', 'mTLS', '流量治理'], maxInstances: 1,
    requirements: [
      { types: ['envoy'], mode: 'all', description: '服务网格需要 Envoy 作为数据面代理。' },
      { types: ['backend-service'], mode: 'any', minCount: 2, description: '服务网格至少需要两个后端服务才能展示服务间治理。' },
    ],
    configFields: [
      { key: 'mtls', label: '双向 TLS', type: 'boolean' },
      { key: 'sampling', label: '追踪采样率', type: 'number', unit: '%', min: 0, max: 100 },
    ],
    defaults: { mtls: true, sampling: 10 },
  },
  {
    type: 'rate-limiter', name: '限流器', subtitle: 'Rate Limiter', category: 'governance', icon: '⏱', color: '#ff986b',
    description: '限制单位时间内允许通过的请求数，保护下游服务不被突发流量压垮。',
    usage: ['与 API 网关或 Envoy 配合', '选择令牌桶或滑动窗口算法', '为超限请求设置明确响应'],
    principles: ['令牌桶允许一定程度的突发流量。', '分布式限流需要共享或近似一致的计数状态。'],
    pitfalls: ['阈值过低会误伤正常流量', '只做入口限流无法隔离内部热点'],
    tags: ['限流', '稳定性', '令牌桶'], maxInstances: 3,
    requirements: [{ types: ['api-gateway', 'envoy'], mode: 'any', description: '限流器需要 API 网关或 Envoy 作为流量执行点。' }],
    configFields: [
      { key: 'algorithm', label: '限流算法', type: 'select', options: ['Token Bucket', 'Leaky Bucket', 'Sliding Window'] },
      { key: 'limit', label: '请求上限', type: 'number', unit: 'req/s', min: 1 },
    ],
    defaults: { algorithm: 'Token Bucket', limit: 500 },
  },
  {
    type: 'prometheus', name: 'Prometheus', subtitle: 'Metrics', category: 'observability', icon: '◉', color: '#ff7b54',
    description: '以时间序列形式采集和查询系统指标，用于监控、告警和容量分析。',
    usage: ['至少添加一个被观测服务', '采集 QPS、错误率、延迟和资源使用率', '通过规则计算聚合指标'],
    principles: ['Prometheus 默认通过 Pull 模式抓取指标。', '标签维度过多会造成时间序列基数爆炸。'],
    pitfalls: ['不要把用户 ID 等高基数字段作为标签', '监控系统自身也需要高可用设计'],
    tags: ['Metrics', '监控', '告警'], maxInstances: 2,
    requirements: [{ types: ['backend-service', 'api-gateway', 'envoy'], mode: 'any', description: 'Prometheus 需要至少一个可观测的服务节点。' }],
    configFields: [
      { key: 'interval', label: '采集间隔', type: 'number', unit: 's', min: 1 },
      { key: 'retention', label: '数据保留', type: 'number', unit: '天', min: 1 },
    ],
    defaults: { interval: 15, retention: 15 },
  },
  {
    type: 'jaeger', name: 'Jaeger', subtitle: 'Distributed Tracing', category: 'observability', icon: '⌁', color: '#59d3c4',
    description: '收集并展示跨服务调用链，帮助定位延迟、错误和依赖关系。',
    usage: ['为服务传播统一 Trace ID', '查看 Span 层级和关键路径', '结合采样控制存储成本'],
    principles: ['Trace 由多个具有父子关系的 Span 组成。', '上下文需要随同步请求和异步消息传播。'],
    pitfalls: ['采样过低可能遗漏偶发故障', '敏感业务数据不应写入 Span 属性'],
    tags: ['Tracing', '链路追踪', 'OpenTelemetry'], maxInstances: 2,
    requirements: [{ types: ['backend-service'], mode: 'any', description: 'Jaeger 需要至少一个后端服务来产生调用链。' }],
    configFields: [
      { key: 'sampling', label: '采样率', type: 'number', unit: '%', min: 0, max: 100 },
      { key: 'propagation', label: '上下文协议', type: 'select', options: ['W3C Trace Context', 'B3', 'Jaeger'] },
    ],
    defaults: { sampling: 10, propagation: 'W3C Trace Context' },
  },
];

export const getDefinition = (type: string) => nodeCatalog.find((item) => item.type === type)!;
